services:
  react-cron-job:
    container_name: react-cron-job
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3008:80
    # volumes:
    #   - ./src:/app/src
    #   - /app/src/node_modules